#!/usr/bin/env python3
"""
Scriptum end-to-end browser tests (Playwright, single-file).

Covers library, reader (Read & Listen), reader-text (Read Only), audio-text
sync, highlights, notes, bookmarks, search, chapter navigation, settings,
themes, sleep timer, speed control, offline/service worker, mobile
responsiveness, and progress persistence.

Audio playback uses silent placeholder MP3s generated by
generate_silent_audio.py (real TTS audio isn't present in the dev container).
The sync tests seek to known timing positions and verify the correct
`.sentence.active` element, which exercises the same code path as real audio.

Usage:
    python3 tests/e2e/run_tests.py [--base-url URL]

Writes PNG screenshots to tests/e2e/screenshots/ and a Markdown report to
tests/e2e/reports/report.md.
"""

import argparse
import json
import re
import sys
import time
import traceback
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, List, Optional

from playwright.sync_api import (
    Browser,
    BrowserContext,
    ConsoleMessage,
    Page,
    Playwright,
    TimeoutError as PWTimeoutError,
    sync_playwright,
)

ROOT = Path(__file__).resolve().parents[2]
SHOTS = ROOT / "tests/e2e/screenshots"
REPORTS = ROOT / "tests/e2e/reports"
DEFAULT_BASE_URL = "http://localhost:8765"
BOOK_ID = "the-intelligent-investor"


@dataclass
class TestResult:
    name: str
    status: str  # "pass" | "fail" | "warn" | "skip"
    duration_ms: int
    screenshot: Optional[str] = None
    details: str = ""
    error: Optional[str] = None
    console_errors: List[str] = field(default_factory=list)


class ScriptumTester:
    def __init__(self, base_url: str, headless: bool = True):
        self.base_url = base_url.rstrip("/")
        self.headless = headless
        self.results: List[TestResult] = []
        self.console_errors: List[str] = []
        self.pw: Optional[Playwright] = None
        self.browser: Optional[Browser] = None
        self.context: Optional[BrowserContext] = None
        self.page: Optional[Page] = None

    # ---------- infra ----------

    def setup(self):
        SHOTS.mkdir(parents=True, exist_ok=True)
        REPORTS.mkdir(parents=True, exist_ok=True)
        for f in SHOTS.glob("*.png"):
            f.unlink()

        self.pw = sync_playwright().start()
        self.browser = self.pw.chromium.launch(
            headless=self.headless,
            args=["--autoplay-policy=no-user-gesture-required"],
        )
        self.context = self.browser.new_context(
            viewport={"width": 1440, "height": 900},
            device_scale_factor=1,
        )
        self.context.grant_permissions([])
        self.page = self.context.new_page()
        self.page.on("console", self._on_console)
        self.page.on("pageerror", lambda err: self.console_errors.append(f"pageerror: {err}"))

    def teardown(self):
        try:
            if self.context:
                self.context.close()
            if self.browser:
                self.browser.close()
            if self.pw:
                self.pw.stop()
        except Exception:
            pass

    def _on_console(self, msg: ConsoleMessage):
        if msg.type in ("error",):
            text = msg.text
            # Ignore noise unrelated to the app under test
            ignore_patterns = (
                "Service Worker",
                "SW]",
                "Proxy Authentication",  # sandbox blocks Google Fonts
                "fonts.googleapis",
                "fonts.gstatic",
                "cdnjs.cloudflare",  # pdf.js CDN in reader-text
                "net::ERR_",  # other network failures
                "Failed to load resource",
            )
            if any(p in text for p in ignore_patterns):
                return
            self.console_errors.append(f"console.{msg.type}: {text}")

    def shot(self, name: str) -> str:
        path = SHOTS / f"{name}.png"
        try:
            self.page.screenshot(path=str(path), full_page=False)
        except Exception as e:
            print(f"  screenshot error {name}: {e}")
        return path.name

    def run(self, name: str, fn: Callable[[], str]):
        print(f"▶ {name}")
        start = time.time()
        errs_before = len(self.console_errors)
        try:
            details = fn() or ""
            dur = int((time.time() - start) * 1000)
            shot = self.shot(self._slug(name))
            new_errs = self.console_errors[errs_before:]
            status = "warn" if new_errs else "pass"
            self.results.append(
                TestResult(name, status, dur, shot, details, console_errors=new_errs)
            )
            tag = "⚠" if new_errs else "✓"
            print(f"  {tag} {name} ({dur} ms)")
            if details:
                print(f"    {details}")
        except Exception as e:
            dur = int((time.time() - start) * 1000)
            shot = self.shot(self._slug(name) + "_FAIL")
            tb = traceback.format_exc()
            new_errs = self.console_errors[errs_before:]
            self.results.append(
                TestResult(
                    name,
                    "fail",
                    dur,
                    shot,
                    "",
                    error=f"{e}\n{tb}",
                    console_errors=new_errs,
                )
            )
            print(f"  ✗ {name} ({dur} ms): {e}")

    @staticmethod
    def _slug(name: str) -> str:
        return re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()

    # ---------- helpers ----------

    def goto_library(self):
        self.page.goto(f"{self.base_url}/web/library.html", wait_until="networkidle")

    def goto_reader(self, book_id: str = BOOK_ID):
        self.page.goto(
            f"{self.base_url}/web/reader.html?book={book_id}",
            wait_until="networkidle",
        )
        # Wait for at least one sentence to render
        self.page.wait_for_selector(".sentence", timeout=15000)

    def goto_reader_text(self, book_id: str = "the-intelligent-investor-text"):
        self.page.goto(
            f"{self.base_url}/web/reader-text.html?book={book_id}",
            wait_until="networkidle",
        )

    def wait_for_timing(self):
        """Wait until timing.json is loaded in the reader (entries[0].start defined)."""
        self.page.wait_for_function(
            """() => {
                const r = window.reader;
                return r && r.timingData && r.timingData.chapters
                    && r.timingData.chapters[0] && r.timingData.chapters[0].entries
                    && r.timingData.chapters[0].entries.length > 0
                    && typeof r.timingData.chapters[0].entries[0].start === 'number';
            }""",
            timeout=15000,
        )

    # ---------- tests ----------

    def test_library_loads(self):
        self.goto_library()
        title = self.page.title()
        assert "Scriptum" in title, f"Unexpected title: {title}"
        self.page.wait_for_selector(".book-card")
        cards = self.page.locator(".book-card").count()
        assert cards >= 1, f"Expected ≥1 book card, got {cards}"
        return f"title='{title}', book cards={cards}"

    def test_library_counts(self):
        converted = self.page.locator("#converted-count").text_content()
        uploaded = self.page.locator("#uploaded-count").text_content()
        assert int(converted) >= 1, f"converted count={converted}"
        return f"converted={converted}, uploaded={uploaded}"

    def test_library_theme_light(self):
        self.page.click("#settings-btn")
        self.page.wait_for_selector("#settings-panel.open .theme-btn[data-theme='light']", state="visible")
        dark_bg = self.page.evaluate("getComputedStyle(document.body).backgroundColor")
        self.page.click("#settings-panel .theme-btn[data-theme='light']")
        self.page.wait_for_function("document.body.dataset.theme === 'light'")
        self.page.wait_for_timeout(250)  # let transitions settle
        light_bg = self.page.evaluate("getComputedStyle(document.body).backgroundColor")
        light_var = self.page.evaluate(
            "getComputedStyle(document.body).getPropertyValue('--bg-primary').trim()"
        )
        assert light_bg != dark_bg, f"light theme bg did not change: {light_bg}"
        return f"dark bg={dark_bg} → light bg={light_bg} (--bg-primary={light_var})"

    def test_library_theme_sepia(self):
        self.page.click("#settings-panel .theme-btn[data-theme='sepia']")
        self.page.wait_for_function("document.body.dataset.theme === 'sepia'")
        self.page.wait_for_timeout(250)
        sepia_bg = self.page.evaluate("getComputedStyle(document.body).backgroundColor")
        self.page.click("#settings-panel .theme-btn[data-theme='dark']")
        # Dark = attribute REMOVED in setTheme()
        self.page.wait_for_function("!document.body.dataset.theme")
        self.page.click("#close-settings")
        self.page.wait_for_function("!document.getElementById('settings-panel').classList.contains('open')")
        return f"sepia bg={sepia_bg}, restored dark"

    def test_library_search(self):
        self.page.click("#search-btn")
        # library toggles #search-bar via inline style (flex/none)
        self.page.wait_for_function(
            "() => document.getElementById('search-bar').style.display === 'flex'"
        )
        self.page.fill("#search-input", "Intelligent")
        self.page.wait_for_timeout(400)
        visible = self.page.locator(".book-card").count()
        self.page.click("#search-close")
        return f"results for 'Intelligent': {visible}"

    def test_library_list_layout(self):
        self.page.click(".view-toggle[data-layout='list']")
        self.page.wait_for_selector(".books-grid.list-layout", timeout=5000)
        self.page.click(".view-toggle[data-layout='grid']")
        self.page.wait_for_function("!document.querySelector('.books-grid.list-layout')", timeout=5000)
        return "list/grid toggle ok"

    def test_navigate_notes_section(self):
        # Expand the Notes sidebar section first (it's collapsed by default)
        self.page.click(".nav-section[data-section='notes'] .nav-section-toggle")
        self.page.wait_for_selector(".nav-section[data-section='notes'].open", timeout=3000)
        self.page.click("[data-view='all-notes']")
        self.page.wait_for_selector("#view-all-notes.active", timeout=5000)
        title = self.page.locator("#page-title").text_content()
        self.page.click("[data-view='converted']")
        self.page.wait_for_selector("#view-converted.active", timeout=5000)
        return f"notes section title='{title}'"

    def test_reader_loads(self):
        # Clear any prior state so resume doesn't skew sync tests
        self.page.evaluate("() => localStorage.clear()")
        self.goto_reader()
        self.wait_for_timing()
        book_title = self.page.locator("#book-title").text_content()
        sentences = self.page.locator(".sentence").count()
        chapters = self.page.locator("#chapter-select option").count()
        assert sentences > 10, f"Expected many sentences, got {sentences}"
        assert chapters >= 40, f"Expected ≥40 chapters, got {chapters}"
        return f"title='{book_title}', sentences={sentences}, chapters={chapters}"

    def test_audio_metadata_loaded(self):
        # Wait for audio duration to be available
        self.page.wait_for_function(
            "() => { const a = document.getElementById('audio'); return a && a.readyState >= 1 && a.duration > 0; }",
            timeout=10000,
        )
        info = self.page.evaluate(
            """() => {
                const a = document.getElementById('audio');
                return { src: a.currentSrc, duration: a.duration, readyState: a.readyState };
            }"""
        )
        assert info["duration"] > 0, f"bad duration: {info}"
        return f"src=..{info['src'][-30:]}, duration={info['duration']:.1f}s, readyState={info['readyState']}"

    def test_play_pause(self):
        self.page.click("#play-pause")
        self.page.wait_for_function(
            "() => { const a = document.getElementById('audio'); return !a.paused && a.currentTime > 0.05; }",
            timeout=5000,
        )
        t_after_play = self.page.evaluate("document.getElementById('audio').currentTime")
        self.page.click("#play-pause")
        self.page.wait_for_function("document.getElementById('audio').paused", timeout=3000)
        paused = self.page.evaluate("document.getElementById('audio').paused")
        return f"playing reached t={t_after_play:.2f}s, paused={paused}"

    def test_audio_text_sync(self):
        """Seek to known timing start and verify the correct .sentence.active."""
        entries = self.page.evaluate(
            "() => window.reader.timingData.chapters[0].entries.slice(0, 20)"
        )
        assert len(entries) >= 5, "need at least 5 timing entries"
        targets = [entries[0], entries[2], entries[4]]
        matched = 0
        details = []
        for entry in targets:
            mid = (entry["start"] + entry["end"]) / 2.0
            self.page.evaluate(
                f"() => {{ const a = document.getElementById('audio'); a.currentTime = {mid}; a.dispatchEvent(new Event('timeupdate')); }}"
            )
            try:
                self.page.wait_for_function(
                    f"""() => {{
                        const el = document.querySelector('.sentence.active');
                        return el && el.dataset.id === '{entry["id"]}';
                    }}""",
                    timeout=4000,
                )
                matched += 1
                details.append(f"t={mid:.2f}s→{entry['id']}")
            except PWTimeoutError:
                active = self.page.evaluate(
                    "() => { const el = document.querySelector('.sentence.active'); return el ? el.dataset.id : null; }"
                )
                details.append(f"t={mid:.2f}s expected={entry['id']} got={active} FAIL")
        assert matched == len(targets), "; ".join(details)
        return f"{matched}/{len(targets)} sync checks passed — " + "; ".join(details)

    def test_click_sentence_seeks_audio(self):
        self.page.evaluate("() => { document.getElementById('audio').currentTime = 0; }")
        # Click the 3rd sentence
        third_id = self.page.evaluate(
            "() => window.reader.timingData.chapters[0].entries[2].id"
        )
        third_start = self.page.evaluate(
            "() => window.reader.timingData.chapters[0].entries[2].start"
        )
        self.page.click(f".sentence[data-id='{third_id}']")
        self.page.wait_for_function(
            f"() => Math.abs(document.getElementById('audio').currentTime - {third_start}) < 0.5",
            timeout=3000,
        )
        t = self.page.evaluate("document.getElementById('audio').currentTime")
        return f"clicked {third_id} → audio t={t:.2f}s (expected ~{third_start:.2f}s)"

    def test_skip_forward_back(self):
        self.page.evaluate("() => { document.getElementById('audio').currentTime = 60; }")
        self.page.wait_for_timeout(100)
        self.page.click("#skip-forward")
        self.page.wait_for_timeout(200)
        t_fwd = self.page.evaluate("document.getElementById('audio').currentTime")
        self.page.click("#skip-back")
        self.page.wait_for_timeout(200)
        t_back = self.page.evaluate("document.getElementById('audio').currentTime")
        assert t_fwd > 60, f"forward did not advance: {t_fwd}"
        assert t_back < t_fwd, f"back did not rewind: {t_back} vs {t_fwd}"
        return f"base=60s, +30→{t_fwd:.1f}s, −10→{t_back:.1f}s"

    def test_speed_control(self):
        self.page.click("#speed-btn")
        # Speed menu is always in DOM; its button just needs clicking
        self.page.click("#speed-menu button[data-speed='1.5']", force=True)
        self.page.wait_for_function("document.getElementById('audio').playbackRate === 1.5")
        speed = self.page.evaluate("document.getElementById('audio').playbackRate")
        label = self.page.locator("#speed-value").text_content()
        # restore
        self.page.click("#speed-btn")
        self.page.click("#speed-menu button[data-speed='1']", force=True)
        self.page.wait_for_function("document.getElementById('audio').playbackRate === 1")
        return f"rate=1.5 → {speed}, label='{label}', restored 1x"

    def test_chapter_navigation(self):
        self.page.select_option("#chapter-select", "1")
        self.page.wait_for_function(
            "() => window.reader.currentChapter === 1", timeout=5000
        )
        self.page.wait_for_selector(".sentence")
        ch = self.page.evaluate("window.reader.currentChapter")
        assert ch == 1
        # back to 0
        self.page.select_option("#chapter-select", "0")
        self.page.wait_for_function("() => window.reader.currentChapter === 0", timeout=5000)
        return "chapter 0 → 1 → 0 ok"

    def test_highlight_via_button(self):
        # Need a current sentence — set via timing then fire timeupdate
        first_id = self.page.evaluate(
            "() => window.reader.timingData.chapters[0].entries[1].id"
        )
        start = self.page.evaluate(
            "() => window.reader.timingData.chapters[0].entries[1].start"
        )
        self.page.evaluate(
            f"() => {{ const a = document.getElementById('audio'); a.currentTime = {start + 0.1}; a.dispatchEvent(new Event('timeupdate')); }}"
        )
        self.page.wait_for_function(
            f"() => document.querySelector('.sentence.active')?.dataset.id === '{first_id}'"
        )
        self.page.click("#highlight-btn")
        self.page.wait_for_selector(f".sentence[data-id='{first_id}'].highlighted", timeout=3000)
        count = self.page.evaluate("window.reader.highlights.length")
        assert count >= 1
        return f"highlighted {first_id}, total highlights={count}"

    def test_note_via_button(self):
        # Add a note via the note button + modal
        self.page.click("#note-btn")
        self.page.wait_for_selector("#notes-modal.open", state="visible", timeout=5000)
        self.page.fill("#note-input", "Automated test note content")
        self.page.click("#save-note")
        # Wait for modal to close
        self.page.wait_for_function(
            "() => !document.getElementById('notes-modal').classList.contains('open')",
            timeout=5000,
        )
        self.page.wait_for_timeout(150)
        note_count = self.page.evaluate("window.reader.notes.length")
        assert note_count >= 1, f"note not saved, notes={note_count}"
        has_note = self.page.evaluate(
            "() => !!document.querySelector('.sentence.has-note')"
        )
        return f"notes={note_count}, .has-note applied={has_note}"

    def test_bookmark(self):
        self.page.evaluate("() => { document.getElementById('audio').currentTime = 12.5; }")
        self.page.wait_for_timeout(100)
        self.page.click("#bookmark-btn")
        self.page.wait_for_timeout(200)
        bookmarks = self.page.evaluate("window.reader.bookmarks.length")
        assert bookmarks >= 1
        # Open bookmarks panel to verify UI
        self.page.click("#menu-btn")
        self.page.wait_for_selector("#bookmarks-panel.open", timeout=3000)
        items = self.page.locator("#bookmarks-list .bookmark-item").count()
        self.page.click("#close-bookmarks")
        return f"bookmarks stored={bookmarks}, UI items={items}"

    def test_search_in_book(self):
        self.page.click("#search-btn")
        self.page.wait_for_selector("#search-modal.open", state="visible", timeout=5000)
        self.page.fill("#search-input", "investor")
        self.page.click("#search-submit")
        self.page.wait_for_timeout(500)
        items = self.page.locator("#search-results .search-result").count()
        self.page.click("#close-search")
        self.page.wait_for_function(
            "() => !document.getElementById('search-modal').classList.contains('open')"
        )
        return f"'investor' → {items} results"

    def test_sleep_timer(self):
        self.page.click("#sleep-timer-btn")
        self.page.wait_for_selector("#sleep-timer-modal.open", state="visible", timeout=5000)
        self.page.click("#sleep-timer-modal button[data-minutes='5']")
        # Selecting an option closes the modal in the reader
        self.page.wait_for_function(
            "() => !document.getElementById('sleep-timer-modal').classList.contains('open')",
            timeout=5000,
        )
        self.page.wait_for_timeout(200)
        has = self.page.evaluate("window.reader.sleepTimerEnd !== null")
        display = self.page.locator("#sleep-timer-display").text_content()
        # cancel timer
        self.page.click("#sleep-timer-btn")
        self.page.wait_for_selector("#sleep-timer-modal.open", state="visible")
        self.page.click("#sleep-timer-modal button[data-minutes='0']")
        self.page.wait_for_function(
            "() => !document.getElementById('sleep-timer-modal').classList.contains('open')"
        )
        return f"timer set={has}, display='{display}'"

    def test_settings_font_size(self):
        self.page.click("#settings-btn")
        self.page.wait_for_selector("#settings-panel.open", timeout=5000)
        before = int(self.page.locator("#font-size-value").text_content().replace("px", ""))
        self.page.click("#font-increase")
        self.page.click("#font-increase")
        after = int(self.page.locator("#font-size-value").text_content().replace("px", ""))
        self.page.click("#close-settings")
        self.page.wait_for_function(
            "() => !document.getElementById('settings-panel').classList.contains('open')"
        )
        assert after > before
        return f"font {before}px → {after}px"

    def test_theme_reader_light(self):
        self.page.click("#settings-btn")
        self.page.wait_for_selector("#settings-panel.open")
        dark_bg = self.page.evaluate("getComputedStyle(document.body).backgroundColor")
        self.page.click("#settings-panel .theme-btn[data-theme='light']")
        self.page.wait_for_function("document.body.dataset.theme === 'light'")
        self.page.wait_for_timeout(250)
        light_bg = self.page.evaluate("getComputedStyle(document.body).backgroundColor")
        assert light_bg != dark_bg, f"reader light theme bg did not change: {light_bg}"
        self.page.click("#settings-panel .theme-btn[data-theme='dark']")
        self.page.wait_for_function("!document.body.dataset.theme")
        self.page.click("#close-settings")
        self.page.wait_for_function(
            "() => !document.getElementById('settings-panel').classList.contains('open')"
        )
        return f"dark bg={dark_bg} → light bg={light_bg}"

    def test_progress_persistence(self):
        # Seek to a known position, reload, verify resume
        self.page.evaluate("() => { document.getElementById('audio').currentTime = 45.5; window.reader.saveProgress(); }")
        self.page.wait_for_timeout(200)
        self.page.reload(wait_until="networkidle")
        self.page.wait_for_selector(".sentence")
        self.wait_for_timing()
        # Give the reader a moment to load saved position
        self.page.wait_for_function(
            "() => { const a = document.getElementById('audio'); return a && a.readyState >= 1 && a.duration > 0; }",
            timeout=10000,
        )
        self.page.wait_for_timeout(500)
        t = self.page.evaluate("document.getElementById('audio').currentTime")
        # Allow some tolerance — reader may round to nearest sentence
        assert t > 30, f"resume position wrong: {t}"
        return f"reloaded, resumed at t={t:.1f}s"

    def test_highlights_persist(self):
        count = self.page.evaluate("window.reader.highlights.length")
        assert count >= 1, f"highlights lost after reload: {count}"
        visible = self.page.locator(".sentence.highlighted").count()
        return f"stored={count}, DOM highlighted={visible}"

    def test_reader_text_loads(self):
        self.goto_reader_text()
        # No actual PDF is wired up for this book, but the shell should render
        self.page.wait_for_selector("#book-title", timeout=5000)
        title = self.page.locator("#book-title").text_content()
        return f"reader-text title='{title}'"

    def test_service_worker_registered(self):
        self.goto_library()
        try:
            self.page.wait_for_function(
                "() => navigator.serviceWorker && navigator.serviceWorker.controller !== null",
                timeout=8000,
            )
            scope = self.page.evaluate(
                "() => navigator.serviceWorker.controller ? navigator.serviceWorker.controller.scriptURL : null"
            )
            return f"SW controller: {scope}"
        except PWTimeoutError:
            # Some browsers need reload
            self.page.reload(wait_until="networkidle")
            self.page.wait_for_function(
                "() => navigator.serviceWorker && navigator.serviceWorker.controller !== null",
                timeout=5000,
            )
            scope = self.page.evaluate(
                "() => navigator.serviceWorker.controller ? navigator.serviceWorker.controller.scriptURL : null"
            )
            return f"SW controller (after reload): {scope}"

    def test_mobile_viewport(self):
        mobile = self.browser.new_context(
            viewport={"width": 390, "height": 844},
            device_scale_factor=2,
            is_mobile=True,
            has_touch=True,
            user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148",
        )
        mp = mobile.new_page()
        try:
            mp.goto(f"{self.base_url}/web/library.html", wait_until="networkidle")
            mp.wait_for_selector(".book-card")
            mp.screenshot(path=str(SHOTS / "mobile_library.png"))
            mp.goto(
                f"{self.base_url}/web/reader.html?book={BOOK_ID}",
                wait_until="networkidle",
            )
            mp.wait_for_selector(".sentence", timeout=15000)
            mp.screenshot(path=str(SHOTS / "mobile_reader.png"))
            return "390×844 library + reader ok"
        finally:
            mobile.close()

    def test_performance_metrics(self):
        self.page.goto(f"{self.base_url}/web/library.html", wait_until="load")
        metrics = self.page.evaluate(
            """() => {
                const t = performance.timing || performance.getEntriesByType('navigation')[0];
                if (performance.getEntriesByType) {
                    const nav = performance.getEntriesByType('navigation')[0];
                    if (nav) return { domContentLoaded: nav.domContentLoadedEventEnd, load: nav.loadEventEnd, ttfb: nav.responseStart };
                }
                return { domContentLoaded: t.domContentLoadedEventEnd - t.navigationStart, load: t.loadEventEnd - t.navigationStart };
            }"""
        )
        return f"DCL={metrics.get('domContentLoaded',0):.0f}ms, load={metrics.get('load',0):.0f}ms, TTFB={metrics.get('ttfb',0):.0f}ms"

    def test_offline_static_cache(self):
        """Verify service worker caches static files by going offline and reloading."""
        # Prime the cache
        self.page.goto(f"{self.base_url}/web/library.html", wait_until="networkidle")
        self.page.wait_for_function(
            "() => navigator.serviceWorker && navigator.serviceWorker.controller !== null",
            timeout=5000,
        )
        self.context.set_offline(True)
        try:
            self.page.reload(wait_until="load", timeout=10000)
            self.page.wait_for_selector(".book-card", timeout=5000)
            title = self.page.title()
        finally:
            self.context.set_offline(False)
        return f"offline reload ok, title='{title}'"

    # ---------- driver ----------

    def run_all(self):
        # Library
        self.run("Library: loads with book cards", self.test_library_loads)
        self.run("Library: counts", self.test_library_counts)
        self.run("Library: theme light", self.test_library_theme_light)
        self.run("Library: theme sepia", self.test_library_theme_sepia)
        self.run("Library: search filter", self.test_library_search)
        self.run("Library: list/grid layout toggle", self.test_library_list_layout)
        self.run("Library: notes section navigation", self.test_navigate_notes_section)

        # Reader
        self.run("Reader: loads with text rendered", self.test_reader_loads)
        self.run("Reader: audio metadata loaded", self.test_audio_metadata_loaded)
        self.run("Reader: play/pause toggles state", self.test_play_pause)
        self.run("Reader: audio→text sync via timeupdate", self.test_audio_text_sync)
        self.run("Reader: click sentence seeks audio", self.test_click_sentence_seeks_audio)
        self.run("Reader: skip +30 / −10", self.test_skip_forward_back)
        self.run("Reader: speed control", self.test_speed_control)
        self.run("Reader: chapter navigation", self.test_chapter_navigation)
        self.run("Reader: highlight via button", self.test_highlight_via_button)
        self.run("Reader: note via button + modal", self.test_note_via_button)
        self.run("Reader: bookmark create + panel list", self.test_bookmark)
        self.run("Reader: in-book search", self.test_search_in_book)
        self.run("Reader: sleep timer", self.test_sleep_timer)
        self.run("Reader: font size increase", self.test_settings_font_size)
        self.run("Reader: theme switching", self.test_theme_reader_light)
        self.run("Reader: progress persists across reload", self.test_progress_persistence)
        self.run("Reader: highlights persist across reload", self.test_highlights_persist)

        # Reader Text (Read Only shell)
        self.run("Reader Text: shell loads", self.test_reader_text_loads)

        # PWA / SW / mobile / perf
        self.run("Service worker registered", self.test_service_worker_registered)
        self.run("Mobile viewport renders", self.test_mobile_viewport)
        self.run("Performance metrics", self.test_performance_metrics)
        self.run("Offline static cache", self.test_offline_static_cache)

    def write_report(self):
        passed = sum(1 for r in self.results if r.status == "pass")
        warned = sum(1 for r in self.results if r.status == "warn")
        failed = sum(1 for r in self.results if r.status == "fail")
        total = len(self.results)

        lines = [
            "# Scriptum Automated Test Report",
            "",
            f"- Base URL: `{self.base_url}`",
            f"- Total: **{total}**  ·  Passed: **{passed}**  ·  Warnings: **{warned}**  ·  Failed: **{failed}**",
            f"- Book under test: `{BOOK_ID}` (46 chapters, silent placeholder audio generated to match timing.json)",
            "",
            "## Summary",
            "",
            "| # | Test | Status | Duration | Details |",
            "|---|------|--------|----------|---------|",
        ]
        for i, r in enumerate(self.results, 1):
            icon = {"pass": "✅", "warn": "⚠️", "fail": "❌", "skip": "⏭"}[r.status]
            details = r.details or (r.error.splitlines()[0] if r.error else "")
            details = details.replace("|", "\\|")[:120]
            lines.append(f"| {i} | {r.name} | {icon} {r.status} | {r.duration_ms} ms | {details} |")

        lines.append("")
        lines.append("## Test Details")
        for i, r in enumerate(self.results, 1):
            icon = {"pass": "✅", "warn": "⚠️", "fail": "❌", "skip": "⏭"}[r.status]
            lines.append(f"\n### {i}. {icon} {r.name}")
            lines.append(f"- Status: **{r.status}**")
            lines.append(f"- Duration: {r.duration_ms} ms")
            if r.details:
                lines.append(f"- Details: {r.details}")
            if r.screenshot:
                lines.append(f"- Screenshot: `screenshots/{r.screenshot}`")
                lines.append(f"\n![{r.name}](../screenshots/{r.screenshot})")
            if r.console_errors:
                lines.append("- Console errors:")
                for ce in r.console_errors:
                    lines.append(f"  - `{ce}`")
            if r.error:
                lines.append("- Error:")
                lines.append("```")
                lines.append(r.error[:2000])
                lines.append("```")

        report = REPORTS / "report.md"
        report.write_text("\n".join(lines))
        print(f"\nReport written to {report}")
        print(f"Screenshots in {SHOTS}")
        return passed, warned, failed, total


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default=DEFAULT_BASE_URL)
    ap.add_argument("--headed", action="store_true")
    args = ap.parse_args()

    tester = ScriptumTester(args.base_url, headless=not args.headed)
    try:
        tester.setup()
        tester.run_all()
    finally:
        passed, warned, failed, total = tester.write_report()
        tester.teardown()
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
